precommit修正

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,6 +1,14 @@
 #!/bin/bash
 
-echo "check" | ./copy_to_subject.sh
+echo -n "Checking unit test before commit..."
+if ! make -C philo/ test > /dev/null 2> /dev/null; then
+	echo "❌"
+	echo "unit test failed. Commit aborted."
+	exit 1
+fi
+echo "✅"
+
+echo "check" | ./copy_to_subject.sh > /dev/null
 echo -n "Checking norminette before commit..."
 if ! norminette check/ > /dev/null 2> >(cat >&2); then
 	echo "❌"
